# Use root/example as user/password credentials
version: '3.1'

services:

  fulbodb:
    build: .
    restart: always
    depends_on:
      - mongo
    ports:
      - 8082:80

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: DB-USER
      MONGO_INITDB_ROOT_PASSWORD: DB-PASSWORD

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: DB-USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: DB-PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://DB-USER:DB-PASSWORD@mongo:27017/